### ISSUE TITLE
Main branch update

### ISSUE THREAD

**Issue by LKay** [LKay/react-bootstrap-datetimepicker#4]
#### Todo List
- [ ] Add full support to controlled input with invalid date preserving #3
- [ ] Add basic tests unit/selenium
- [ ] Add support for multi formats by utilising `extraFormats` option
- [x] Add support for debug mode and keeping open and closing dialog
- [x] Add focus to input field when dialog is open
- [ ] Add support for disabled and enabled hours (`enabledHours`, `disabledHours`)
- [ ] Add support for displaying calendar weeks on the left ([`calendarWeeks`](https://eonasdan.github.io/bootstrap-datetimepicker/Options/#calendarweeks))
- [ ] Add support for disabled time intervals
